export const providerOptions = [
  { label: 'DeepSeek 深度求索 (deepseek)', value: 'deepseek' },
  { label: '智谱 AI / GLM (zhipu)', value: 'zhipu' },
  { label: '通义千问 / 阿里云百炼 (qianwen)', value: 'qianwen' },
  { label: '月之暗面 Kimi (moonshot)', value: 'moonshot' },
  { label: 'Ollama 私有大模型 (ollama)', value: 'ollama' },
  { label: 'OpenAI / ChatGPT (openai)', value: 'openai' },
  { label: 'Anthropic Claude (claude)', value: 'claude' },
  { label: 'Google Gemini (gemini)', value: 'gemini' },
  { label: '字节跳动 豆包 (doubao)', value: 'doubao' },
  { label: '百度 文心一言 (baidu)', value: 'baidu' },
  { label: '腾讯 混元大模型 (hunyuan)', value: 'hunyuan' },
  { label: '百川智能 (baichuan)', value: 'baichuan' },
  { label: 'MiniMax (minimax)', value: 'minimax' },
  { label: '零一万物 (yi)', value: 'yi' },
  { label: '科大讯飞 星火 (spark)', value: 'spark' },
  { label: '阶跃星辰 (stepfun)', value: 'stepfun' },
  { label: '商汤 日日新 (sensenova)', value: 'sensenova' },
  { label: 'Mistral AI (mistral)', value: 'mistral' },
  { label: 'PPIO (ppio)', value: 'ppio' },
  { label: '小米 MiMo (xiaomi)', value: 'xiaomi' },
];
